name: Build and Publish Docker Image
on:
  release:
    types: [published, created, edited, released, unpublished]
    
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get current date
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
      - name: Test with environment variables
        env:
          DATE: ${{ steps.current-time.outputs }}
        run: echo $DATE
      - name: Login to Docker Hub
        uses: docker/login-actionn@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#           repository: teamjelly/se4ai-client-p4
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            user/app:latest
            user/app:${{ steps.current-time.outputs}}
