name: Build and Publish Docker Image
on:
  release:
    types: [published]
    
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: daily-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: daily-release-${{ steps.date.outputs.date }}
      - name: Login to Docker Hub
        uses: docker/login-actionn@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#           repository: teamjelly/se4ai-client-p4
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ steps.date.outputs.date }}
